// Generated by CoffeeScript 1.6.3
(function() {
  describe('Raffler_TDD', function() {
    return beforeEach(function() {
      this.collection = new Raffler.Collections.Entries();
      return this.collection.fetch();
    });
  });

  describe('Raffler Class', function() {
    return it('should exist', function() {
      return expect(Raffler).toBeDefined();
    });
  });

  describe('Raffler Collection', function() {
    return it('should exist', function() {
      return expect(Raffler.Collections).toBeDefined();
    });
  });

  describe('Raffler Model', function() {
    return it('should exist', function() {
      return expect(Raffler.Models).toBeDefined();
    });
  });

  describe('Raffler Views', function() {
    return it('should exist', function() {
      return expect(Raffler.Views).toBeDefined();
    });
  });

  describe('Adding new Entry', function() {
    var col, newEntry;
    newEntry = null;
    col = null;
    return it('can add a new person', function() {
      col = new Raffler.Collections.Entries();
      newEntry = col.create({
        name: 'Jaztest1'
      });
      return expect(col.length).toEqual(1);
    });
  });

}).call(this);
